import { TimeOfDay } from '@/utils/notifications';

export interface HabitTemplate {
  id: string;
  category: 'Popular' | 'Mind & Focus' | 'Learning' | 'Health & Wellness';
  icon: string;
  name: string;
  description: string;
  color: string;
  time_of_day: TimeOfDay | TimeOfDay[];
  frequency: 'daily' | 'weekly';
  target_days?: number[];
  completion_type: 'check' | 'time' | 'quantity';
  planned_time_minutes?: number;
  target_value?: number;
  target_unit?: string;
  reminder_message?: string;
}

export const HABIT_TEMPLATES: HabitTemplate[] = [
  // POPULAR
  {
    id: 'reading',
    category: 'Popular',
    icon: 'BookIcon',
    name: 'Reading every day',
    description: 'Read for 20 minutes',
    color: 'yellow',
    time_of_day: 'anytime',
    frequency: 'daily',
    completion_type: 'time',
    planned_time_minutes: 20,
    target_value: 20,
    target_unit: 'minutes',
    reminder_message: 'Time to dive into your book!',
  },
  {
    id: 'water',
    category: 'Popular',
    icon: 'MugIcon',
    name: 'Drink more water',
    description: 'Stay hydrated every day',
    color: 'blue',
    time_of_day: 'anytime',
    frequency: 'daily',
    completion_type: 'quantity',
    target_value: 8,
    target_unit: 'glasses',
    reminder_message: 'Have a glass of refreshing water!',
  },
  {
    id: 'exercise',
    category: 'Popular',
    icon: 'ActivityIcon',
    name: 'Exercise',
    description: 'Move your body for 30 minutes',
    color: 'green',
    time_of_day: 'morning',
    frequency: 'daily',
    completion_type: 'time',
    planned_time_minutes: 30,
    target_value: 30,
    target_unit: 'minutes',
    reminder_message: 'Time to get active and energized!',
  },
  {
    id: 'daily_walk',
    category: 'Popular',
    icon: 'WatchIcon',
    name: 'Daily steps',
    description: 'Hit 8,000 steps today',
    color: 'cyan',
    time_of_day: 'anytime',
    frequency: 'daily',
    completion_type: 'quantity',
    target_value: 8000,
    target_unit: 'steps',
    reminder_message: 'Time for a walk to reach your step goal!',
  },

  // MIND & FOCUS
  {
    id: 'meditate',
    category: 'Mind & Focus',
    icon: 'LampIcon',
    name: 'Meditate',
    description: 'Take 10 minutes for yourself',
    color: 'cyan',
    time_of_day: 'morning',
    frequency: 'daily',
    completion_type: 'time',
    planned_time_minutes: 10,
    target_value: 10,
    target_unit: 'minutes',
    reminder_message: 'Pause and take a mindful breath.',
  },
  {
    id: 'journal',
    category: 'Mind & Focus',
    icon: 'EditIcon',
    name: 'Journal',
    description: 'Reflect on your day',
    color: 'yellow',
    time_of_day: 'evening',
    frequency: 'daily',
    completion_type: 'check',
    reminder_message: 'Time to put your thoughts on paper.',
  },
  {
    id: 'screen_time',
    category: 'Mind & Focus',
    icon: 'BellDisabledIcon',
    name: 'Reduce screen time',
    description: 'Spend less time scrolling',
    color: 'pink',
    time_of_day: 'evening',
    frequency: 'daily',
    completion_type: 'check',
    reminder_message: 'Unplug and unwind for the night.',
  },
  {
    id: 'deep_focus',
    category: 'Mind & Focus',
    icon: 'ClockIcon',
    name: 'Deep focus block',
    description: '45 mins distraction-free work',
    color: 'orange',
    time_of_day: 'morning',
    frequency: 'daily',
    completion_type: 'time',
    planned_time_minutes: 45,
    target_value: 45,
    target_unit: 'minutes',
    reminder_message: 'Start your focused work session now.',
  },

  // LEARNING
  {
    id: 'coding',
    category: 'Learning',
    icon: 'KeyboardIcon',
    name: 'Practice coding',
    description: 'Improve your programming skills',
    color: 'orange',
    time_of_day: 'afternoon',
    frequency: 'daily',
    completion_type: 'time',
    planned_time_minutes: 45,
    target_value: 45,
    target_unit: 'minutes',
    reminder_message: 'Code session time — build something cool!',
  },
  {
    id: 'language',
    category: 'Learning',
    icon: 'BookIcon',
    name: 'Learn a language',
    description: 'Practice every day',
    color: 'blue',
    time_of_day: 'anytime',
    frequency: 'daily',
    completion_type: 'time',
    planned_time_minutes: 15,
    target_value: 15,
    target_unit: 'minutes',
    reminder_message: 'Practice your vocabulary today!',
  },
  {
    id: 'study',
    category: 'Learning',
    icon: 'DocumentIcon',
    name: 'Study',
    description: 'Make time to learn',
    color: 'green',
    time_of_day: 'afternoon',
    frequency: 'daily',
    completion_type: 'time',
    planned_time_minutes: 30,
    target_value: 30,
    target_unit: 'minutes',
    reminder_message: 'Focus session: make time to learn.',
  },
  {
    id: 'creativity',
    category: 'Learning',
    icon: 'BrushIcon',
    name: 'Creative art',
    description: 'Draw, paint or design',
    color: 'orange',
    time_of_day: 'evening',
    frequency: 'daily',
    completion_type: 'time',
    planned_time_minutes: 20,
    target_value: 20,
    target_unit: 'minutes',
    reminder_message: 'Time to express your creativity today!',
  },
  {
    id: 'music',
    category: 'Learning',
    icon: 'MusicNoteIcon',
    name: 'Practice instrument',
    description: 'Play music for 20 minutes',
    color: 'pink',
    time_of_day: 'afternoon',
    frequency: 'daily',
    completion_type: 'time',
    planned_time_minutes: 20,
    target_value: 20,
    target_unit: 'minutes',
    reminder_message: 'Time to play your instrument and practice music!',
  },

  // HEALTH & WELLNESS
  {
    id: 'vitamins',
    category: 'Health & Wellness',
    icon: 'ShieldIcon',
    name: 'Take vitamins',
    description: 'Daily supplements and health',
    color: 'blue',
    time_of_day: 'morning',
    frequency: 'daily',
    completion_type: 'check',
    reminder_message: 'Take your daily vitamins and nutrients.',
  },
  {
    id: 'sleep',
    category: 'Health & Wellness',
    icon: 'MoonIcon',
    name: 'Sleep well',
    description: 'Get 8 hours of restful sleep',
    color: 'orange',
    time_of_day: 'evening',
    frequency: 'daily',
    completion_type: 'time',
    planned_time_minutes: 480,
    target_value: 8,
    target_unit: 'hours',
    reminder_message: 'Wind down and prepare for a great sleep.',
  },
  {
    id: 'skincare',
    category: 'Health & Wellness',
    icon: 'SparklesIcon',
    name: 'Skincare routine',
    description: 'Morning & evening self-care',
    color: 'pink',
    time_of_day: ['morning', 'evening'],
    frequency: 'daily',
    completion_type: 'check',
    reminder_message: 'Time for your refreshing skincare routine!',
  },
  {
    id: 'early_wake',
    category: 'Health & Wellness',
    icon: 'AlarmIcon',
    name: 'Wake up early',
    description: 'Start your morning with focus',
    color: 'red',
    time_of_day: 'morning',
    frequency: 'daily',
    completion_type: 'check',
    reminder_message: 'Good morning! Time to start the day.',
  },
  {
    id: 'healthy_meals',
    category: 'Health & Wellness',
    icon: 'BasketIcon',
    name: 'Eat clean',
    description: 'Healthy and wholesome nutrition',
    color: 'green',
    time_of_day: 'anytime',
    frequency: 'daily',
    completion_type: 'check',
    reminder_message: 'Time to enjoy a healthy meal!',
  },
];

export const TEMPLATE_CATEGORIES = [
  'Popular',
  'Mind & Focus',
  'Learning',
  'Health & Wellness',
] as const;

